version: "3.9"  # optional since v1.27.0
services:
  etl:
    build: .
    image: fun-etl/airflow
    ports:
      - "8080:8080"
    # command: airflow webserver
    volumes:
      - $PWD/src:/opt/src:ro
      # - logvolume01:/var/log
    # environment:
    #  - AIRFLOW_HOME=/opt/src