version: "3.9"  # optional since v1.27.0
services:
  etl:
    build: .
    image: fun-etl/airflow
    ports:
      - "8080:8080"
    # command: airflow webserver
    volumes:
      # - $PWD/src/airflow/airflow.cfg:/opt/src/airflow.cfg:ro
      # - $PWD/src/airflow/unittests.cfg:/opt/src/unittests.cfg:ro
      # - $PWD/src/airflow/webserver_config.py:/opt/src/unittests.cfg:ro
      - $PWD/src/airflow:/opt/src/airflow
      # - logvolume01:/var/log
    # environment:
    #  - AIRFLOW_HOME=/opt/src