version: "3.9"  # optional since v1.27.0
services:
  etl:
    build: .
    image: fun-etl/airflow
    ports:
      - "8080:8080"
    command: /bin/bash
    volumes:
      - $PWD/src:/opt/src
      # - logvolume01:/var/log